version: '3.7'

services:
  node:
    image: oliviercuyp/hello-js
    build: .
    command: npm run start:dev
    ports:
      - 3000:3000
    environment:
      APP_PORT: 3000
      NAME: JS
    volumes:
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./src:/opt/src
